package com.airbag.dis.disfoot

val SHARED_PREFERENCES_KEY = "SHARED_PREFERENCES_KEY"
val SHARED_PREFERENCES_KEY_BOARDED = "SHARED_PREFERENCES_KEY_BOARDED"
val SHARED_PREFERENCES_KEY_REGISTERED = "SHARED_PREFERENCES_KEY_REGISTERED"